
version: '3'
services:
  mongo:
    build: ./db/
    ports:
     - "27017:27017"

  app:
    build: ./dev/
    ports:
     - "8000:8000"
    links:
     - mongo
    environment:
     - INCIDENTS_DB_SERVER_NAME=3c07334f386a