
version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
     - "27017:27017"
    hostname: 'incident_MongoServer'

  app:
    build: ./dev/
    ports:
     - "8000:8000"
    links:
     - mongo
    environment:
     - INCIDENTS_DB_SERVER_NAME=incident_MongoServer
     - INCIDENTS_MONGO_URI=
     - INCIDENTS_RETRY_LIMIT=10
